default: &default
  :concurrency: <%= ENV['WORKER_CONCURRENCY'] || ENV['RAILS_MAX_THREADS'] || 5 %>
  # Set timeout to 8 on Heroku, longer if you manage your own systems.
  :timeout: 8

development:
  <<: *default

heroku:
  <<: *default

staging:
  <<: *default

production:
  <<: *default

# Sidekiq will run this file through ERB when reading it so you can
# even put in dynamic logic, like a host-specific queue.
# http://www.mikeperham.com/2013/11/13/advanced-sidekiq-host-specific-queues/
queues:
  - mailers
  - default
